export enum ROLES_NAMES {
  CORE_TEAM = 'CORE_TEAM',
  MODERATORS = 'MODERATORS',
  MVPS = 'MVPS',
  LIBRARY_MAINTAINERS = 'LIBRARY_MAINTAINERS',
  COMMUNITY_LEADERS = 'COMMUNITY_LEADERS',
  NITRO_BOOSTERS = 'NITRO_BOOSTERS',
}

export enum ROLES_FRIENDLY_NAMES {
  CORE_TEAM = 'Core Team',
  MODERATORS = 'Moderators',
  MVPS = 'MVPs',
  LIBRARY_MAINTAINERS = 'Library Maintainers',
  COMMUNITY_LEADERS = 'Community Leaders',
  NITRO_BOOSTERS = 'Nitro Boosters',
}
